# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BuildInstanceType:
    Type: CommaDelimitedList
    Default: "t3.large"
    Description: Instance Type
  S3AnsibleBucket:
    Type: String
    Description: Enter bucketname that contains ansible playbooks
    Default: ansible-playbook
  S3BucketPrefix:
    Type: String
    Description: Enter bucket prefix
    Default: container
  PlaybookFileName:
    Type: String
    Description: Enter playbook filename
    Default: playbook.yml
  RepositoryName:
    Type: String
    Description: Enter ECR Repository name
    Default: devdays


Resources:
  ECRRepo: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration: True
      ImageTagMutability: IMMUTABLE
  ImageBuilderLogBucket:
    Type: AWS::S3::Bucket
  InstanceRole:
    Type: AWS::IAM::Role
    Metadata:
      Comment: Role to be used by instance during image build.
    Properties:
      RoleName: Ansible-ECR
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AWSImageBuilderFullAccess
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonS3ReadOnlyAccess
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMFullAccess
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/CloudWatchAgentServerPolicy
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMPatchAssociation
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: "2012-10-17"
      Path: /executionServiceEC2Role/
  InstanceRoleLoggingPolicy:
    Type: AWS::IAM::Policy
    Metadata:
      Comment: Allows the instance to save log files to an S3 bucket.
    Properties:
      PolicyName: ImageBuilderLogBucketPolicy
      Roles:
        - Ref: InstanceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - s3:PutObject
            Effect: Allow
            Resource:
              - Fn::Sub:
                  - arn:${AWS::Partition}:s3:::${BUCKET}/*
                  - BUCKET:
                      Ref: ImageBuilderLogBucket
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /executionServiceEC2Role/
      Roles:
        - Ref: InstanceRole
  Amazon2ImageInfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: ECR-Infrastructure-Configuration
      Description: Standard Intrastructure Configuration
      InstanceProfileName:
        Ref: InstanceProfile
      InstanceTypes:
        Ref: BuildInstanceType
      Logging:
        S3Logs:
          S3BucketName:
            Ref: ImageBuilderLogBucket
          S3KeyPrefix: !Join [ "-", [ 'imagebuilder', !Ref "AWS::StackName" ] ]
  InstallAnsibleComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: Ansible-ECR
      Version: 1.0.0
      Description: Insall Ansible Playbook
      ChangeDescription: First version
      Platform: Linux
      Data: !Sub |
        name: 'Ansible Playbook Execution on Amazon Linux 2'
        description: 'This is a sample component that demonstrates how to download and execute an Ansible playbook against Amazon Linux 2.'
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: CreatingFolderWithOverwrite
                action: CreateFolder
                inputs:
                  - path: /tmp/ansible/
                    overwrite: false
              - name: DownloadPlaybook
                action: S3Download
                inputs:
                  - source: s3://${S3AnsibleBucket}/${S3BucketPrefix}/*
                    destination: /tmp/ansible/
              - name: InstallAnsible
                action: ExecuteBash
                inputs:
                  commands:
                  - amazon-linux-extras install -y ansible2
              - name: InvokeAnsible
                action: ExecuteBash
                inputs:
                  commands:
                  - ansible-playbook /tmp/ansible/${PlaybookFileName}
  AnsibleContainerRecipe:
    Type: AWS::ImageBuilder::ContainerRecipe
    Properties:
      Name: Ansible-Container
      Version: 0.0.1
      
      # ${AWS::Partition} returns the partition where you are running the CloudFormation template. For standard AWS regions, the
      # partition is aws. For resources elsewhere, the partition is aws-partitionname. For example, China (Beijing and Ningxia)
      # regions use aws-cn and AWS GovCloud (US) regions are aws-us-gov.
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html
      ParentImage:
        Fn::Sub: arn:${AWS::Partition}:imagebuilder:${AWS::Region}:aws:image/amazon-linux-x86-latest/x.x.x
      ContainerType: 'DOCKER'
      Components:
        - ComponentArn:
            Ref: InstallAnsibleComponent
      TargetRepository:
            Service: 'ECR'
            RepositoryName: !Ref RepositoryName
      DockerfileTemplateData: |
          FROM {{{ imagebuilder:parentImage }}}
          {{{ imagebuilder:environments }}}
          {{{ imagebuilder:components }}}
          RUN systemctl enable httpd       
  AnsibleDistributionConfiguration:
    Type: 'AWS::ImageBuilder::DistributionConfiguration'
    Properties:
      Name: Ansible-ECR-Distribution
      Description: 'Local region distribution'
      Distributions:
        - Region: 
            Fn::Sub: ${AWS::Region}
          ContainerDistributionConfiguration:
            Description: Distribution for region
            TargetRepository:
              Service: ECR
              RepositoryName: !Ref RepositoryName
  AnsibleImagePipeline:
    Type: 'AWS::ImageBuilder::ImagePipeline'
    Properties:
      Name: 'Ansible-ECR'
      Description: 'Ansible Image Pipeline'
      ContainerRecipeArn: !Ref AnsibleContainerRecipe
      InfrastructureConfigurationArn: !Ref Amazon2ImageInfrastructureConfiguration
      DistributionConfigurationArn: !Ref AnsibleDistributionConfiguration
      Status: 'ENABLED'