---
- name: install the latest version of httpd
  yum: name=httpd state=latest
 
- name: httpd service state
  service: name=httpd state=started enabled=yes

- name: Setting default HTTP Server page
  shell: echo "<h1>welcome to the Ansible Playbook Demo</h1>" >> /var/www/html/index.html